### ISSUE TITLE
Failed to load the laravel-helper package

### ISSUE THREAD

**Issue by finchy70** [73CN0109y-Packages/laravel-helper#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [laravel-helper](https://github.com/73CN0109y-Packages/laravel-helper) package 0.1.0

### Stack Trace

Failed to load the laravel-helper package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/laravel-helper/lib/CommandSelectList.js:13:26)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/laravel-helper/lib/laravel-helper.js:3:41)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:565:22)
    at PackageManager.module.exports.PackageManager.loadPackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:495:27)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:643:36)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:58.7.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -1:27.9.0 pane:split-left-and-copy-active-item (input.hidden-input)
```

### Non-Core Packages

```
atom-laravel-snippets 0.2.0 
blade-snippets 0.2.0 
language-blade 0.32.0 
laravel 0.7.1 
laravel-5-snippets 0.8.0 
laravel-eloquent-snippets 2.0.0 
laravel-forms-bootstrap-snippets 1.2.0 
laravel-helper 0.1.0 
laravel-snippets 2.1.0 
```

**Comment by Tecnology73** [comment]
Should be solved in the latest version (0.1.1)
